package com.lezhi.app.test.mapper;

import com.lezhi.app.test.model.LianjiaHang;
import com.lezhi.app.test.model.LianjiaHangExample;
import com.lezhi.app.test.model.LianjiaHangKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface LianjiaHangMapper {

    int count();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    int deleteByExample(LianjiaHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    int deleteByPrimaryKey(LianjiaHangKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    int insert(LianjiaHang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    int insertSelective(LianjiaHang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    List<LianjiaHang> find(RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    LianjiaHang selectByPrimaryKey(LianjiaHangKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    int updateByExampleSelective(@Param("record") LianjiaHang record, @Param("example") LianjiaHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    int updateByExample(@Param("record") LianjiaHang record, @Param("example") LianjiaHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    int updateByPrimaryKeySelective(LianjiaHang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    int updateByPrimaryKey(LianjiaHang record);
}