package com.lezhi.app.test.model;

import java.math.BigDecimal;
import java.util.Date;

public class LianjiaHang extends LianjiaHangKey {


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        LianjiaHang that = (LianjiaHang) o;

        if (propertyArea != null ? !propertyArea.equals(that.propertyArea) : that.propertyArea != null) return false;
        if (placeFloor != null ? !placeFloor.equals(that.placeFloor) : that.placeFloor != null) return false;
        return residenceId != null ? residenceId.equals(that.residenceId) : that.residenceId == null;

    }

    @Override
    public int hashCode() {
        int result = propertyArea != null ? propertyArea.hashCode() : 0;
        result = 31 * result + (placeFloor != null ? placeFloor.hashCode() : 0);
        result = 31 * result + (residenceId != null ? residenceId.hashCode() : 0);
        return result;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.quotation_id
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private Long quotationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.block
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private String block;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.district
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.quotation_total_price
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private BigDecimal quotationTotalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.quotation_unit_price
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private BigDecimal quotationUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.quotation_date
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private Date quotationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.property_area
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private String propertyArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.house_type
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private String houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.property_room
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private Byte propertyRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.property_ting
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private Byte propertyTing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.place_floor
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private String placeFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.total_floor
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private Short totalFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.towards
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private String towards;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.is_available
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private Boolean isAvailable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.residence_id
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private Long residenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.address
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.residence_name
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private String residenceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.last_deal_date
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private Date lastDealDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.create_time
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.modify_time
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.quotation_id
     *
     * @return the value of lianjia_house_quotation_201608.quotation_id
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Long getQuotationId() {
        return quotationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.quotation_id
     *
     * @param quotationId the value for lianjia_house_quotation_201608.quotation_id
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setQuotationId(Long quotationId) {
        this.quotationId = quotationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.block
     *
     * @return the value of lianjia_house_quotation_201608.block
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public String getBlock() {
        return block;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.block
     *
     * @param block the value for lianjia_house_quotation_201608.block
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setBlock(String block) {
        this.block = block == null ? null : block.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.district
     *
     * @return the value of lianjia_house_quotation_201608.district
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.district
     *
     * @param district the value for lianjia_house_quotation_201608.district
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.quotation_total_price
     *
     * @return the value of lianjia_house_quotation_201608.quotation_total_price
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public BigDecimal getQuotationTotalPrice() {
        return quotationTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.quotation_total_price
     *
     * @param quotationTotalPrice the value for lianjia_house_quotation_201608.quotation_total_price
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setQuotationTotalPrice(BigDecimal quotationTotalPrice) {
        this.quotationTotalPrice = quotationTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.quotation_unit_price
     *
     * @return the value of lianjia_house_quotation_201608.quotation_unit_price
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public BigDecimal getQuotationUnitPrice() {
        return quotationUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.quotation_unit_price
     *
     * @param quotationUnitPrice the value for lianjia_house_quotation_201608.quotation_unit_price
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setQuotationUnitPrice(BigDecimal quotationUnitPrice) {
        this.quotationUnitPrice = quotationUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.quotation_date
     *
     * @return the value of lianjia_house_quotation_201608.quotation_date
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Date getQuotationDate() {
        return quotationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.quotation_date
     *
     * @param quotationDate the value for lianjia_house_quotation_201608.quotation_date
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setQuotationDate(Date quotationDate) {
        this.quotationDate = quotationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.property_area
     *
     * @return the value of lianjia_house_quotation_201608.property_area
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public String getPropertyArea() {
        return propertyArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.property_area
     *
     * @param propertyArea the value for lianjia_house_quotation_201608.property_area
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setPropertyArea(String propertyArea) {
        this.propertyArea = propertyArea == null ? null : propertyArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.house_type
     *
     * @return the value of lianjia_house_quotation_201608.house_type
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.house_type
     *
     * @param houseType the value for lianjia_house_quotation_201608.house_type
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType == null ? null : houseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.property_room
     *
     * @return the value of lianjia_house_quotation_201608.property_room
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Byte getPropertyRoom() {
        return propertyRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.property_room
     *
     * @param propertyRoom the value for lianjia_house_quotation_201608.property_room
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setPropertyRoom(Byte propertyRoom) {
        this.propertyRoom = propertyRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.property_ting
     *
     * @return the value of lianjia_house_quotation_201608.property_ting
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Byte getPropertyTing() {
        return propertyTing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.property_ting
     *
     * @param propertyTing the value for lianjia_house_quotation_201608.property_ting
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setPropertyTing(Byte propertyTing) {
        this.propertyTing = propertyTing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.place_floor
     *
     * @return the value of lianjia_house_quotation_201608.place_floor
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public String getPlaceFloor() {
        return placeFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.place_floor
     *
     * @param placeFloor the value for lianjia_house_quotation_201608.place_floor
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setPlaceFloor(String placeFloor) {
        this.placeFloor = placeFloor == null ? null : placeFloor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.total_floor
     *
     * @return the value of lianjia_house_quotation_201608.total_floor
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Short getTotalFloor() {
        return totalFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.total_floor
     *
     * @param totalFloor the value for lianjia_house_quotation_201608.total_floor
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setTotalFloor(Short totalFloor) {
        this.totalFloor = totalFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.towards
     *
     * @return the value of lianjia_house_quotation_201608.towards
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public String getTowards() {
        return towards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.towards
     *
     * @param towards the value for lianjia_house_quotation_201608.towards
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setTowards(String towards) {
        this.towards = towards == null ? null : towards.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.is_available
     *
     * @return the value of lianjia_house_quotation_201608.is_available
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Boolean getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.is_available
     *
     * @param isAvailable the value for lianjia_house_quotation_201608.is_available
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setIsAvailable(Boolean isAvailable) {
        this.isAvailable = isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.residence_id
     *
     * @return the value of lianjia_house_quotation_201608.residence_id
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Long getResidenceId() {
        return residenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.residence_id
     *
     * @param residenceId the value for lianjia_house_quotation_201608.residence_id
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setResidenceId(Long residenceId) {
        this.residenceId = residenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.address
     *
     * @return the value of lianjia_house_quotation_201608.address
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.address
     *
     * @param address the value for lianjia_house_quotation_201608.address
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.residence_name
     *
     * @return the value of lianjia_house_quotation_201608.residence_name
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public String getResidenceName() {
        return residenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.residence_name
     *
     * @param residenceName the value for lianjia_house_quotation_201608.residence_name
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setResidenceName(String residenceName) {
        this.residenceName = residenceName == null ? null : residenceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.last_deal_date
     *
     * @return the value of lianjia_house_quotation_201608.last_deal_date
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Date getLastDealDate() {
        return lastDealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.last_deal_date
     *
     * @param lastDealDate the value for lianjia_house_quotation_201608.last_deal_date
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setLastDealDate(Date lastDealDate) {
        this.lastDealDate = lastDealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.create_time
     *
     * @return the value of lianjia_house_quotation_201608.create_time
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.create_time
     *
     * @param createTime the value for lianjia_house_quotation_201608.create_time
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.modify_time
     *
     * @return the value of lianjia_house_quotation_201608.modify_time
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.modify_time
     *
     * @param modifyTime the value for lianjia_house_quotation_201608.modify_time
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}