package com.lezhi.app.test.model;

public class LianjiaHangKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.id
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianjia_house_quotation_201608.craw_num
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    private String crawNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.id
     *
     * @return the value of lianjia_house_quotation_201608.id
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.id
     *
     * @param id the value for lianjia_house_quotation_201608.id
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianjia_house_quotation_201608.craw_num
     *
     * @return the value of lianjia_house_quotation_201608.craw_num
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public String getCrawNum() {
        return crawNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianjia_house_quotation_201608.craw_num
     *
     * @param crawNum the value for lianjia_house_quotation_201608.craw_num
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setCrawNum(String crawNum) {
        this.crawNum = crawNum == null ? null : crawNum.trim();
    }
}