package com.lezhi.app.test.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LianjiaHangExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public LianjiaHangExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCrawNumIsNull() {
            addCriterion("craw_num is null");
            return (Criteria) this;
        }

        public Criteria andCrawNumIsNotNull() {
            addCriterion("craw_num is not null");
            return (Criteria) this;
        }

        public Criteria andCrawNumEqualTo(String value) {
            addCriterion("craw_num =", value, "crawNum");
            return (Criteria) this;
        }

        public Criteria andCrawNumNotEqualTo(String value) {
            addCriterion("craw_num <>", value, "crawNum");
            return (Criteria) this;
        }

        public Criteria andCrawNumGreaterThan(String value) {
            addCriterion("craw_num >", value, "crawNum");
            return (Criteria) this;
        }

        public Criteria andCrawNumGreaterThanOrEqualTo(String value) {
            addCriterion("craw_num >=", value, "crawNum");
            return (Criteria) this;
        }

        public Criteria andCrawNumLessThan(String value) {
            addCriterion("craw_num <", value, "crawNum");
            return (Criteria) this;
        }

        public Criteria andCrawNumLessThanOrEqualTo(String value) {
            addCriterion("craw_num <=", value, "crawNum");
            return (Criteria) this;
        }

        public Criteria andCrawNumLike(String value) {
            addCriterion("craw_num like", value, "crawNum");
            return (Criteria) this;
        }

        public Criteria andCrawNumNotLike(String value) {
            addCriterion("craw_num not like", value, "crawNum");
            return (Criteria) this;
        }

        public Criteria andCrawNumIn(List<String> values) {
            addCriterion("craw_num in", values, "crawNum");
            return (Criteria) this;
        }

        public Criteria andCrawNumNotIn(List<String> values) {
            addCriterion("craw_num not in", values, "crawNum");
            return (Criteria) this;
        }

        public Criteria andCrawNumBetween(String value1, String value2) {
            addCriterion("craw_num between", value1, value2, "crawNum");
            return (Criteria) this;
        }

        public Criteria andCrawNumNotBetween(String value1, String value2) {
            addCriterion("craw_num not between", value1, value2, "crawNum");
            return (Criteria) this;
        }

        public Criteria andQuotationIdIsNull() {
            addCriterion("quotation_id is null");
            return (Criteria) this;
        }

        public Criteria andQuotationIdIsNotNull() {
            addCriterion("quotation_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuotationIdEqualTo(Long value) {
            addCriterion("quotation_id =", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdNotEqualTo(Long value) {
            addCriterion("quotation_id <>", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdGreaterThan(Long value) {
            addCriterion("quotation_id >", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("quotation_id >=", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdLessThan(Long value) {
            addCriterion("quotation_id <", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdLessThanOrEqualTo(Long value) {
            addCriterion("quotation_id <=", value, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdIn(List<Long> values) {
            addCriterion("quotation_id in", values, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdNotIn(List<Long> values) {
            addCriterion("quotation_id not in", values, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdBetween(Long value1, Long value2) {
            addCriterion("quotation_id between", value1, value2, "quotationId");
            return (Criteria) this;
        }

        public Criteria andQuotationIdNotBetween(Long value1, Long value2) {
            addCriterion("quotation_id not between", value1, value2, "quotationId");
            return (Criteria) this;
        }

        public Criteria andBlockIsNull() {
            addCriterion("block is null");
            return (Criteria) this;
        }

        public Criteria andBlockIsNotNull() {
            addCriterion("block is not null");
            return (Criteria) this;
        }

        public Criteria andBlockEqualTo(String value) {
            addCriterion("block =", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockNotEqualTo(String value) {
            addCriterion("block <>", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockGreaterThan(String value) {
            addCriterion("block >", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockGreaterThanOrEqualTo(String value) {
            addCriterion("block >=", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockLessThan(String value) {
            addCriterion("block <", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockLessThanOrEqualTo(String value) {
            addCriterion("block <=", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockLike(String value) {
            addCriterion("block like", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockNotLike(String value) {
            addCriterion("block not like", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockIn(List<String> values) {
            addCriterion("block in", values, "block");
            return (Criteria) this;
        }

        public Criteria andBlockNotIn(List<String> values) {
            addCriterion("block not in", values, "block");
            return (Criteria) this;
        }

        public Criteria andBlockBetween(String value1, String value2) {
            addCriterion("block between", value1, value2, "block");
            return (Criteria) this;
        }

        public Criteria andBlockNotBetween(String value1, String value2) {
            addCriterion("block not between", value1, value2, "block");
            return (Criteria) this;
        }

        public Criteria andDistrictIsNull() {
            addCriterion("district is null");
            return (Criteria) this;
        }

        public Criteria andDistrictIsNotNull() {
            addCriterion("district is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictEqualTo(String value) {
            addCriterion("district =", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotEqualTo(String value) {
            addCriterion("district <>", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictGreaterThan(String value) {
            addCriterion("district >", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("district >=", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLessThan(String value) {
            addCriterion("district <", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLessThanOrEqualTo(String value) {
            addCriterion("district <=", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLike(String value) {
            addCriterion("district like", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotLike(String value) {
            addCriterion("district not like", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictIn(List<String> values) {
            addCriterion("district in", values, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotIn(List<String> values) {
            addCriterion("district not in", values, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictBetween(String value1, String value2) {
            addCriterion("district between", value1, value2, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotBetween(String value1, String value2) {
            addCriterion("district not between", value1, value2, "district");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceIsNull() {
            addCriterion("quotation_total_price is null");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceIsNotNull() {
            addCriterion("quotation_total_price is not null");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceEqualTo(BigDecimal value) {
            addCriterion("quotation_total_price =", value, "quotationTotalPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("quotation_total_price <>", value, "quotationTotalPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("quotation_total_price >", value, "quotationTotalPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("quotation_total_price >=", value, "quotationTotalPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceLessThan(BigDecimal value) {
            addCriterion("quotation_total_price <", value, "quotationTotalPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("quotation_total_price <=", value, "quotationTotalPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceIn(List<BigDecimal> values) {
            addCriterion("quotation_total_price in", values, "quotationTotalPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("quotation_total_price not in", values, "quotationTotalPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quotation_total_price between", value1, value2, "quotationTotalPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quotation_total_price not between", value1, value2, "quotationTotalPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceIsNull() {
            addCriterion("quotation_unit_price is null");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceIsNotNull() {
            addCriterion("quotation_unit_price is not null");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceEqualTo(BigDecimal value) {
            addCriterion("quotation_unit_price =", value, "quotationUnitPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceNotEqualTo(BigDecimal value) {
            addCriterion("quotation_unit_price <>", value, "quotationUnitPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceGreaterThan(BigDecimal value) {
            addCriterion("quotation_unit_price >", value, "quotationUnitPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("quotation_unit_price >=", value, "quotationUnitPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceLessThan(BigDecimal value) {
            addCriterion("quotation_unit_price <", value, "quotationUnitPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("quotation_unit_price <=", value, "quotationUnitPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceIn(List<BigDecimal> values) {
            addCriterion("quotation_unit_price in", values, "quotationUnitPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceNotIn(List<BigDecimal> values) {
            addCriterion("quotation_unit_price not in", values, "quotationUnitPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quotation_unit_price between", value1, value2, "quotationUnitPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationUnitPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quotation_unit_price not between", value1, value2, "quotationUnitPrice");
            return (Criteria) this;
        }

        public Criteria andQuotationDateIsNull() {
            addCriterion("quotation_date is null");
            return (Criteria) this;
        }

        public Criteria andQuotationDateIsNotNull() {
            addCriterion("quotation_date is not null");
            return (Criteria) this;
        }

        public Criteria andQuotationDateEqualTo(Date value) {
            addCriterionForJDBCDate("quotation_date =", value, "quotationDate");
            return (Criteria) this;
        }

        public Criteria andQuotationDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("quotation_date <>", value, "quotationDate");
            return (Criteria) this;
        }

        public Criteria andQuotationDateGreaterThan(Date value) {
            addCriterionForJDBCDate("quotation_date >", value, "quotationDate");
            return (Criteria) this;
        }

        public Criteria andQuotationDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("quotation_date >=", value, "quotationDate");
            return (Criteria) this;
        }

        public Criteria andQuotationDateLessThan(Date value) {
            addCriterionForJDBCDate("quotation_date <", value, "quotationDate");
            return (Criteria) this;
        }

        public Criteria andQuotationDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("quotation_date <=", value, "quotationDate");
            return (Criteria) this;
        }

        public Criteria andQuotationDateIn(List<Date> values) {
            addCriterionForJDBCDate("quotation_date in", values, "quotationDate");
            return (Criteria) this;
        }

        public Criteria andQuotationDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("quotation_date not in", values, "quotationDate");
            return (Criteria) this;
        }

        public Criteria andQuotationDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("quotation_date between", value1, value2, "quotationDate");
            return (Criteria) this;
        }

        public Criteria andQuotationDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("quotation_date not between", value1, value2, "quotationDate");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaIsNull() {
            addCriterion("property_area is null");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaIsNotNull() {
            addCriterion("property_area is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaEqualTo(String value) {
            addCriterion("property_area =", value, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaNotEqualTo(String value) {
            addCriterion("property_area <>", value, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaGreaterThan(String value) {
            addCriterion("property_area >", value, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaGreaterThanOrEqualTo(String value) {
            addCriterion("property_area >=", value, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaLessThan(String value) {
            addCriterion("property_area <", value, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaLessThanOrEqualTo(String value) {
            addCriterion("property_area <=", value, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaLike(String value) {
            addCriterion("property_area like", value, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaNotLike(String value) {
            addCriterion("property_area not like", value, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaIn(List<String> values) {
            addCriterion("property_area in", values, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaNotIn(List<String> values) {
            addCriterion("property_area not in", values, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaBetween(String value1, String value2) {
            addCriterion("property_area between", value1, value2, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andPropertyAreaNotBetween(String value1, String value2) {
            addCriterion("property_area not between", value1, value2, "propertyArea");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIsNull() {
            addCriterion("house_type is null");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIsNotNull() {
            addCriterion("house_type is not null");
            return (Criteria) this;
        }

        public Criteria andHouseTypeEqualTo(String value) {
            addCriterion("house_type =", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotEqualTo(String value) {
            addCriterion("house_type <>", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeGreaterThan(String value) {
            addCriterion("house_type >", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("house_type >=", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLessThan(String value) {
            addCriterion("house_type <", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLessThanOrEqualTo(String value) {
            addCriterion("house_type <=", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLike(String value) {
            addCriterion("house_type like", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotLike(String value) {
            addCriterion("house_type not like", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIn(List<String> values) {
            addCriterion("house_type in", values, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotIn(List<String> values) {
            addCriterion("house_type not in", values, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeBetween(String value1, String value2) {
            addCriterion("house_type between", value1, value2, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotBetween(String value1, String value2) {
            addCriterion("house_type not between", value1, value2, "houseType");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomIsNull() {
            addCriterion("property_room is null");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomIsNotNull() {
            addCriterion("property_room is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomEqualTo(Byte value) {
            addCriterion("property_room =", value, "propertyRoom");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomNotEqualTo(Byte value) {
            addCriterion("property_room <>", value, "propertyRoom");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomGreaterThan(Byte value) {
            addCriterion("property_room >", value, "propertyRoom");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomGreaterThanOrEqualTo(Byte value) {
            addCriterion("property_room >=", value, "propertyRoom");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomLessThan(Byte value) {
            addCriterion("property_room <", value, "propertyRoom");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomLessThanOrEqualTo(Byte value) {
            addCriterion("property_room <=", value, "propertyRoom");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomIn(List<Byte> values) {
            addCriterion("property_room in", values, "propertyRoom");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomNotIn(List<Byte> values) {
            addCriterion("property_room not in", values, "propertyRoom");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomBetween(Byte value1, Byte value2) {
            addCriterion("property_room between", value1, value2, "propertyRoom");
            return (Criteria) this;
        }

        public Criteria andPropertyRoomNotBetween(Byte value1, Byte value2) {
            addCriterion("property_room not between", value1, value2, "propertyRoom");
            return (Criteria) this;
        }

        public Criteria andPropertyTingIsNull() {
            addCriterion("property_ting is null");
            return (Criteria) this;
        }

        public Criteria andPropertyTingIsNotNull() {
            addCriterion("property_ting is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyTingEqualTo(Byte value) {
            addCriterion("property_ting =", value, "propertyTing");
            return (Criteria) this;
        }

        public Criteria andPropertyTingNotEqualTo(Byte value) {
            addCriterion("property_ting <>", value, "propertyTing");
            return (Criteria) this;
        }

        public Criteria andPropertyTingGreaterThan(Byte value) {
            addCriterion("property_ting >", value, "propertyTing");
            return (Criteria) this;
        }

        public Criteria andPropertyTingGreaterThanOrEqualTo(Byte value) {
            addCriterion("property_ting >=", value, "propertyTing");
            return (Criteria) this;
        }

        public Criteria andPropertyTingLessThan(Byte value) {
            addCriterion("property_ting <", value, "propertyTing");
            return (Criteria) this;
        }

        public Criteria andPropertyTingLessThanOrEqualTo(Byte value) {
            addCriterion("property_ting <=", value, "propertyTing");
            return (Criteria) this;
        }

        public Criteria andPropertyTingIn(List<Byte> values) {
            addCriterion("property_ting in", values, "propertyTing");
            return (Criteria) this;
        }

        public Criteria andPropertyTingNotIn(List<Byte> values) {
            addCriterion("property_ting not in", values, "propertyTing");
            return (Criteria) this;
        }

        public Criteria andPropertyTingBetween(Byte value1, Byte value2) {
            addCriterion("property_ting between", value1, value2, "propertyTing");
            return (Criteria) this;
        }

        public Criteria andPropertyTingNotBetween(Byte value1, Byte value2) {
            addCriterion("property_ting not between", value1, value2, "propertyTing");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorIsNull() {
            addCriterion("place_floor is null");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorIsNotNull() {
            addCriterion("place_floor is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorEqualTo(String value) {
            addCriterion("place_floor =", value, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorNotEqualTo(String value) {
            addCriterion("place_floor <>", value, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorGreaterThan(String value) {
            addCriterion("place_floor >", value, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorGreaterThanOrEqualTo(String value) {
            addCriterion("place_floor >=", value, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorLessThan(String value) {
            addCriterion("place_floor <", value, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorLessThanOrEqualTo(String value) {
            addCriterion("place_floor <=", value, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorLike(String value) {
            addCriterion("place_floor like", value, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorNotLike(String value) {
            addCriterion("place_floor not like", value, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorIn(List<String> values) {
            addCriterion("place_floor in", values, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorNotIn(List<String> values) {
            addCriterion("place_floor not in", values, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorBetween(String value1, String value2) {
            addCriterion("place_floor between", value1, value2, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andPlaceFloorNotBetween(String value1, String value2) {
            addCriterion("place_floor not between", value1, value2, "placeFloor");
            return (Criteria) this;
        }

        public Criteria andTotalFloorIsNull() {
            addCriterion("total_floor is null");
            return (Criteria) this;
        }

        public Criteria andTotalFloorIsNotNull() {
            addCriterion("total_floor is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFloorEqualTo(Short value) {
            addCriterion("total_floor =", value, "totalFloor");
            return (Criteria) this;
        }

        public Criteria andTotalFloorNotEqualTo(Short value) {
            addCriterion("total_floor <>", value, "totalFloor");
            return (Criteria) this;
        }

        public Criteria andTotalFloorGreaterThan(Short value) {
            addCriterion("total_floor >", value, "totalFloor");
            return (Criteria) this;
        }

        public Criteria andTotalFloorGreaterThanOrEqualTo(Short value) {
            addCriterion("total_floor >=", value, "totalFloor");
            return (Criteria) this;
        }

        public Criteria andTotalFloorLessThan(Short value) {
            addCriterion("total_floor <", value, "totalFloor");
            return (Criteria) this;
        }

        public Criteria andTotalFloorLessThanOrEqualTo(Short value) {
            addCriterion("total_floor <=", value, "totalFloor");
            return (Criteria) this;
        }

        public Criteria andTotalFloorIn(List<Short> values) {
            addCriterion("total_floor in", values, "totalFloor");
            return (Criteria) this;
        }

        public Criteria andTotalFloorNotIn(List<Short> values) {
            addCriterion("total_floor not in", values, "totalFloor");
            return (Criteria) this;
        }

        public Criteria andTotalFloorBetween(Short value1, Short value2) {
            addCriterion("total_floor between", value1, value2, "totalFloor");
            return (Criteria) this;
        }

        public Criteria andTotalFloorNotBetween(Short value1, Short value2) {
            addCriterion("total_floor not between", value1, value2, "totalFloor");
            return (Criteria) this;
        }

        public Criteria andTowardsIsNull() {
            addCriterion("towards is null");
            return (Criteria) this;
        }

        public Criteria andTowardsIsNotNull() {
            addCriterion("towards is not null");
            return (Criteria) this;
        }

        public Criteria andTowardsEqualTo(String value) {
            addCriterion("towards =", value, "towards");
            return (Criteria) this;
        }

        public Criteria andTowardsNotEqualTo(String value) {
            addCriterion("towards <>", value, "towards");
            return (Criteria) this;
        }

        public Criteria andTowardsGreaterThan(String value) {
            addCriterion("towards >", value, "towards");
            return (Criteria) this;
        }

        public Criteria andTowardsGreaterThanOrEqualTo(String value) {
            addCriterion("towards >=", value, "towards");
            return (Criteria) this;
        }

        public Criteria andTowardsLessThan(String value) {
            addCriterion("towards <", value, "towards");
            return (Criteria) this;
        }

        public Criteria andTowardsLessThanOrEqualTo(String value) {
            addCriterion("towards <=", value, "towards");
            return (Criteria) this;
        }

        public Criteria andTowardsLike(String value) {
            addCriterion("towards like", value, "towards");
            return (Criteria) this;
        }

        public Criteria andTowardsNotLike(String value) {
            addCriterion("towards not like", value, "towards");
            return (Criteria) this;
        }

        public Criteria andTowardsIn(List<String> values) {
            addCriterion("towards in", values, "towards");
            return (Criteria) this;
        }

        public Criteria andTowardsNotIn(List<String> values) {
            addCriterion("towards not in", values, "towards");
            return (Criteria) this;
        }

        public Criteria andTowardsBetween(String value1, String value2) {
            addCriterion("towards between", value1, value2, "towards");
            return (Criteria) this;
        }

        public Criteria andTowardsNotBetween(String value1, String value2) {
            addCriterion("towards not between", value1, value2, "towards");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIsNull() {
            addCriterion("is_available is null");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIsNotNull() {
            addCriterion("is_available is not null");
            return (Criteria) this;
        }

        public Criteria andIsAvailableEqualTo(Boolean value) {
            addCriterion("is_available =", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotEqualTo(Boolean value) {
            addCriterion("is_available <>", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableGreaterThan(Boolean value) {
            addCriterion("is_available >", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_available >=", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableLessThan(Boolean value) {
            addCriterion("is_available <", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableLessThanOrEqualTo(Boolean value) {
            addCriterion("is_available <=", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIn(List<Boolean> values) {
            addCriterion("is_available in", values, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotIn(List<Boolean> values) {
            addCriterion("is_available not in", values, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableBetween(Boolean value1, Boolean value2) {
            addCriterion("is_available between", value1, value2, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_available not between", value1, value2, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andResidenceIdIsNull() {
            addCriterion("residence_id is null");
            return (Criteria) this;
        }

        public Criteria andResidenceIdIsNotNull() {
            addCriterion("residence_id is not null");
            return (Criteria) this;
        }

        public Criteria andResidenceIdEqualTo(Long value) {
            addCriterion("residence_id =", value, "residenceId");
            return (Criteria) this;
        }

        public Criteria andResidenceIdNotEqualTo(Long value) {
            addCriterion("residence_id <>", value, "residenceId");
            return (Criteria) this;
        }

        public Criteria andResidenceIdGreaterThan(Long value) {
            addCriterion("residence_id >", value, "residenceId");
            return (Criteria) this;
        }

        public Criteria andResidenceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("residence_id >=", value, "residenceId");
            return (Criteria) this;
        }

        public Criteria andResidenceIdLessThan(Long value) {
            addCriterion("residence_id <", value, "residenceId");
            return (Criteria) this;
        }

        public Criteria andResidenceIdLessThanOrEqualTo(Long value) {
            addCriterion("residence_id <=", value, "residenceId");
            return (Criteria) this;
        }

        public Criteria andResidenceIdIn(List<Long> values) {
            addCriterion("residence_id in", values, "residenceId");
            return (Criteria) this;
        }

        public Criteria andResidenceIdNotIn(List<Long> values) {
            addCriterion("residence_id not in", values, "residenceId");
            return (Criteria) this;
        }

        public Criteria andResidenceIdBetween(Long value1, Long value2) {
            addCriterion("residence_id between", value1, value2, "residenceId");
            return (Criteria) this;
        }

        public Criteria andResidenceIdNotBetween(Long value1, Long value2) {
            addCriterion("residence_id not between", value1, value2, "residenceId");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andResidenceNameIsNull() {
            addCriterion("residence_name is null");
            return (Criteria) this;
        }

        public Criteria andResidenceNameIsNotNull() {
            addCriterion("residence_name is not null");
            return (Criteria) this;
        }

        public Criteria andResidenceNameEqualTo(String value) {
            addCriterion("residence_name =", value, "residenceName");
            return (Criteria) this;
        }

        public Criteria andResidenceNameNotEqualTo(String value) {
            addCriterion("residence_name <>", value, "residenceName");
            return (Criteria) this;
        }

        public Criteria andResidenceNameGreaterThan(String value) {
            addCriterion("residence_name >", value, "residenceName");
            return (Criteria) this;
        }

        public Criteria andResidenceNameGreaterThanOrEqualTo(String value) {
            addCriterion("residence_name >=", value, "residenceName");
            return (Criteria) this;
        }

        public Criteria andResidenceNameLessThan(String value) {
            addCriterion("residence_name <", value, "residenceName");
            return (Criteria) this;
        }

        public Criteria andResidenceNameLessThanOrEqualTo(String value) {
            addCriterion("residence_name <=", value, "residenceName");
            return (Criteria) this;
        }

        public Criteria andResidenceNameLike(String value) {
            addCriterion("residence_name like", value, "residenceName");
            return (Criteria) this;
        }

        public Criteria andResidenceNameNotLike(String value) {
            addCriterion("residence_name not like", value, "residenceName");
            return (Criteria) this;
        }

        public Criteria andResidenceNameIn(List<String> values) {
            addCriterion("residence_name in", values, "residenceName");
            return (Criteria) this;
        }

        public Criteria andResidenceNameNotIn(List<String> values) {
            addCriterion("residence_name not in", values, "residenceName");
            return (Criteria) this;
        }

        public Criteria andResidenceNameBetween(String value1, String value2) {
            addCriterion("residence_name between", value1, value2, "residenceName");
            return (Criteria) this;
        }

        public Criteria andResidenceNameNotBetween(String value1, String value2) {
            addCriterion("residence_name not between", value1, value2, "residenceName");
            return (Criteria) this;
        }

        public Criteria andLastDealDateIsNull() {
            addCriterion("last_deal_date is null");
            return (Criteria) this;
        }

        public Criteria andLastDealDateIsNotNull() {
            addCriterion("last_deal_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastDealDateEqualTo(Date value) {
            addCriterionForJDBCDate("last_deal_date =", value, "lastDealDate");
            return (Criteria) this;
        }

        public Criteria andLastDealDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("last_deal_date <>", value, "lastDealDate");
            return (Criteria) this;
        }

        public Criteria andLastDealDateGreaterThan(Date value) {
            addCriterionForJDBCDate("last_deal_date >", value, "lastDealDate");
            return (Criteria) this;
        }

        public Criteria andLastDealDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("last_deal_date >=", value, "lastDealDate");
            return (Criteria) this;
        }

        public Criteria andLastDealDateLessThan(Date value) {
            addCriterionForJDBCDate("last_deal_date <", value, "lastDealDate");
            return (Criteria) this;
        }

        public Criteria andLastDealDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("last_deal_date <=", value, "lastDealDate");
            return (Criteria) this;
        }

        public Criteria andLastDealDateIn(List<Date> values) {
            addCriterionForJDBCDate("last_deal_date in", values, "lastDealDate");
            return (Criteria) this;
        }

        public Criteria andLastDealDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("last_deal_date not in", values, "lastDealDate");
            return (Criteria) this;
        }

        public Criteria andLastDealDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("last_deal_date between", value1, value2, "lastDealDate");
            return (Criteria) this;
        }

        public Criteria andLastDealDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("last_deal_date not between", value1, value2, "lastDealDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 31 11:02:15 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lianjia_house_quotation_201608
     *
     * @mbggenerated Wed Aug 31 11:02:15 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}